# Generated by Django 2.2.4 on 2019-08-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(upload_to='resume_folder')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.Intern')),
            ],
        ),
    ]
