# Generated by Django 2.2.4 on 2019-08-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signup1',
            unique_together={('full_name', 'email', 'internship')},
        ),
    ]
